---

- hosts: localhost
  become: True
  become_user: root
  connection: local
  gather_facts: False
  vars:
    app_dir: /home/ken/apps
    user_name: ken
    repo_name: /tmp/fa-repo.dpkg      
    
  tasks:
    - name: blacklist the default driver
      ansible.builtin.lineinfile: 
        path: /etc/modprobe.d/blacklist-dvb.conf
        line: "blacklist dvb_usb_rtl28xxu"
        create: true
        
    - name: install rtl-sdr drivers
      ansible.builtin.apt:
        name: rtl-sdr
        state: present
        #force_apt_get: true

    - name: add the rule file to the thingy
      ansible.builtin.lineinfile: 
        path: /etc/udev/rules.d/20.rtlsdr.rules
        line: SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", GROUP="adm", MODE="0666", SYMLINK+="rtl_sdr"
        create: true
        
    - name: restart udev
      ansible.builtin.systemd:
        name: udev
        state: restarted
        
    - name: create app folder
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ user_name }}"
        
#    - name: download CubicSDR file
#      ansible.builtin.get_url:
#        url: https://github.com/cjcliffe/CubicSDR/releases/download/0.2.5/CubicSDR-0.2.5-x86_64.AppImage
#        dest: "{{ app_dir }}" 
#        owner: "{{ user_name }}"
#        mode: '0755'

    - name: install CubicSDR
      ansible.builtin.apt:
        name: cubicsdr
        state: present
        #force_apt_get: true
        
    - name: download GQRX file
      ansible.builtin.get_url:
        url: https://github.com/gqrx-sdr/gqrx/releases/download/v2.16/Gqrx-2.16-x86_64.AppImage
        dest: "{{ app_dir }}" 
        owner: "{{ user_name }}"
        mode: '0755'
        
    - name: install rtl-433 
      ansible.builtin.apt:
        name: rtl-433
        state: present
        #force_apt_get: true

    #- name: install dump1090-fa
    #  block:
        #- name: get the FA repo
        #  ansible.builtin.get_url:
        #    url: https://flightaware.com/adsb/piaware/files/packages/pool/piaware/f/flightaware-apt-repository/flightaware-apt-repository_1.1_all.deb
        #    dest: "{{ repo_name }}"

        #- name: install FA repo
        #  command: dpkg -i {{ repo_name }}

          # This didn't work, but from the command line it did.
          # And I don't think the stuff above is necessary
        #- name: install dump1090 package
        #  ansible.builtin.apt:
        #    update_cache: true
        #    name: dump1090-fa
        #    force_apt_get: true
        #    state: present

