---

# Well, this is sort of ok.  The real set of commands are in misc/condensedAiInstallation.txt
# It's best to build a lot of stuff from source, as there are quirks and architectural stuff.
# So this playbook is not really up-to-date.
# See misc/SmartV5Bookworm.txt to see the exact versions of RPi and Pi OS that were used
  
- hosts: localhost
  become: True
  become_user: root
  connection: local
  gather_facts: True
  vars:
    app_dir: /home/ken/apps
    user_name: ken
    repo_name: /tmp/fa-repo.dpkg      
    gqrx_version: "2.17.5"
    
  tasks:
	- name: Configure RTL-SDR kernel module blacklist
	  ansible.builtin.copy:
		content: |
		  blacklist dvb_usb_rtl28xxu
		  blacklist rtl2832
		  blacklist rtl2830
		  blacklist rtl2832_sdr
		dest: /etc/modprobe.d/rtl-sdr-blacklist.conf
		mode: '0644'
        
	- name: Configure USB power management
	  ansible.builtin.shell: echo 'options usbcore autosuspend=-1' > /etc/modprobe.d/usb-autosuspend.conf
	  args:
		creates: /etc/modprobe.d/usb-autosuspend.conf
	
	- name: install rtl-sdr drivers
      ansible.builtin.apt:
        name: rtl-sdr
        state: present
        #force_apt_get: true

        
    - name: create app folder
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ user_name }}"
        
#    - name: download CubicSDR file
#      ansible.builtin.get_url:
#        url: https://github.com/cjcliffe/CubicSDR/releases/download/0.2.5/CubicSDR-0.2.5-x86_64.AppImage
#        dest: "{{ app_dir }}" 
#        owner: "{{ user_name }}"
#        mode: '0755'

    - name: install CubicSDR
      ansible.builtin.apt:
        name: cubicsdr
        state: present
        #force_apt_get: true
        
# This doesn't work, because the RPi is not x86 architecture, it's ARM. GQRX is only windows, mac, and x86 AppImage
#    - name: download GQRX file
#      ansible.builtin.get_url:
#        url: https://github.com/gqrx-sdr/gqrx/releases/download/v{{ gqrx_version }}/Gqrx-{{ gqrx_version }}-x86_64.AppImage
#        dest: "{{ app_dir }}" 
#        owner: "{{ user_name }}"
#        mode: '0755'
        
    - name: install rtl-433 
      ansible.builtin.apt:
        name: rtl-433
        state: present
        #force_apt_get: true
        
#    - name: copy rtl_433 service file
#      ansible.builtin.copy:
#        src: rtl_433.service
#        dest: /etc/systemd/system/rtl_433.service
#        owner: root
#        group: root
#        mode: '0644'        
#
#    - name: Enable and start rtl_433 service
#      ansible.builtin.systemd:
#        name: rtl_433
#        enabled: true
#        state: started

    #- name: install dump1090-fa
    #  block:
        #- name: get the FA repo
        #  ansible.builtin.get_url:
        #    url: https://flightaware.com/adsb/piaware/files/packages/pool/piaware/f/flightaware-apt-repository/flightaware-apt-repository_1.1_all.deb
        #    dest: "{{ repo_name }}"

        #- name: install FA repo
        #  command: dpkg -i {{ repo_name }}

          # This didn't work, but from the command line it did.
          # And I don't think the stuff above is necessary
        #- name: install dump1090 package
        #  ansible.builtin.apt:
        #    update_cache: true
        #    name: dump1090-fa
        #    force_apt_get: true
        #    state: present

