---

# This playbook assumes you have installed rtl_sdr and rtl-433 and that those are working!
# See the misc/condensedAiInstalltion.txt for the script.
  
- hosts: localhost
  become: True
  become_user: root
  connection: local
  gather_facts: True
  vars:
    weewx_root: /etc/weewx  # https://www.weewx.com/docs/5.1/usersguide/where/
    weewx_home: /opt/weewx
    weewx_html: "{{ weewx_home }}/html"
    weewx_database: "{{ weewx_home }}/data"
      
    
  tasks:
    # DOCS AT https://weewx.com/docs/5.0/
    # https://weewx.com/docs/5.0/quickstarts/debian/
    # See also  https://github.com/vinceskahan/weewx-sdr-howto/blob/main/howto.txt
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - wget
          - gpg
        update_cache: yes
      register: apt_result
    
#      Why use "buster" instead of "bookworm":
#
#      The repository metadata identifies itself as "buster" even when accessed as "bookworm"
#      This is common when repositories haven't been fully updated for newer Debian versions 7
#      Modern key handling:
#
#      The keyring parameter in apt_key ensures proper GPG key storage in the modern location
#      Avoids the deprecated /etc/apt/trusted.gpg approach mentioned in your warnings
#      Repository structure explanation:
#
#      deb [arch=all signed-by=/usr/share/keyrings/weewx-archive-keyring.gpg] https://weewx.com/apt/python3 buster main
#      |_________| |______________________________________________________| |_________________________| |______| |____|
#          |                      |                                               |                    |       |
#      Options              Key specification                                Repository URL       Distribution Component
      
      
    - name: Add Weewx repository key
      ansible.builtin.apt_key:
        url: https://weewx.com/keys.html
        keyring: /usr/share/keyrings/weewx-archive-keyring.gpg
        state: present

    - name: Add Weewx repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=all signed-by=/usr/share/keyrings/weewx-archive-keyring.gpg] https://weewx.com/apt/python3 buster main"
        state: present
        filename: weewx
        update_cache: yes
          
      # AI prefers the task above to this 
#    - name: add weewx repository
#      ansible.builtin.shell: echo "deb [arch=all] https://weewx.com/apt/python3 bookworm stable" | sudo tee /etc/apt/sources.list.d/weewx.list
      
#    - name: get the weewx pubkey
#      ansible.builtin.shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ED444FCCF0E2B09E

      # bleh, there's a quiz when you install it by hand.  "apt-get remove weewx; apt-get install weewx"
      # actually, it installed for me ok on 5.0.2-1
    - name: install weewx
      ansible.builtin.apt:
        name: weewx, nginx
        update_cache: yes
       
      # SDR driver: https://github.com/matthewwall/weewx-sdr
      # https://github.com/matthewwall/weewx-sdr/issues/183  for the 5.0 version
    - name: get the SDR driver
      #ansible.builtin.shell: wget -O weewx-sdr.zip https://github.com/matthewwall/weewx-sdr/archive/master.zip
      ansible.builtin.shell: weectl extension install -y https://github.com/matthewwall/weewx-sdr/archive/master.zip
      args:
        creates: /etc/weewx/bin/user/sdr.py
      
    - name: Add weewx user to adm group
      ansible.builtin.user:
        name: weewx
        groups: 
          - weewx
          - adm
          - plugdev

    - name: create the custom weewx SSD directories
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: '0755'
        owner: weewx
      loop:
        - "{{ weewx_html }}"
        - "{{ weewx_database }}"
        
    - name: create weewx conf file
      ansible.builtin.template:
        src: weewx.conf
        dest: "{{ weewx_root }}/weewx.conf"
        mode: '0644'
      
    - name: create nginx conf file
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'
        
    - name: restart weewx service
      ansible.builtin.service:
        name: weewx
        state: restarted
        enabled: yes

    - name: restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
        
    - name: Create safe database backup
      cron:
        name: "weewx database backup"
        minute: "12"
        job: "sqlite3 {{ weewx_database }}/weewx.sdb \".timeout 2000\" \".backup weewx-backup.sdb\""
        
        
# logs: sudo tail -f /var/log/syslog | grep weewx
#       sudo journalctl -u weewx -f    
# https://weewx.com/docs/5.1/usersguide/monitoring/#logging-on-macos
# https://github.com/weewx/weewx/wiki/WeeWX-v4-and-logging
#[Logging]
#    # Path to dedicated log file
#    log_file = /var/log/weewx/weewx.log
#    
#    # Log level (1=errors only, 2=errors/warnings, 3=verbose)
#    log_level = 2
#    
#    # Rotate logs when they reach 10MB
#    log_rotate_interval = 10000000
#    
#    # Keep 7 rotated logs
#    log_rotate_files = 7
#    
#    # Optional: Log timestamps in local time
#    log_console_time = True    
