---

# This playbook assumes you have installed rtl_sdr and rtl-433 and that those are working!
# See the misc/condensedAiInstalltion.txt for the script.
  
- hosts: localhost
  become: True
  become_user: root
  connection: local
  gather_facts: True
  vars:
    weewx_root: /etc/weewx  # https://www.weewx.com/docs/5.1/usersguide/where/
    weewx_home: /opt/weewx
    weewx_html: "{{ weewx_home }}/html"
    weewx_database: "{{ weewx_home }}/data"
      
    
  tasks:
    # DOCS AT https://weewx.com/docs/5.0/
    # https://weewx.com/docs/5.0/quickstarts/debian/
    # See also  https://github.com/vinceskahan/weewx-sdr-howto/blob/main/howto.txt
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - wget
          - gpg
        update_cache: yes
      register: apt_result
    
    - name: Add Weewx repository key
      ansible.builtin.apt_key:
        url: https://weewx.com/keys.html
        state: present
  
    # INSTEAD OF SHELL COMMANDS
    - name: Add Weewx repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=all] https://weewx.com/apt/python3 {{ ansible_distribution_release }} stable"
        state: present
        filename: weewx

      # AI prefers the task above to this 
#    - name: add weewx repository
#      ansible.builtin.shell: echo "deb [arch=all] https://weewx.com/apt/python3 bookworm stable" | sudo tee /etc/apt/sources.list.d/weewx.list
      
#    - name: get the weewx pubkey
#      ansible.builtin.shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ED444FCCF0E2B09E

      # bleh, there's a quiz when you install it by hand.  "apt-get remove weewx; apt-get install weewx"
      # actually, it installed for me ok on 5.0.2-1
    - name: install weewx
      ansible.builtin.apt:
        name: weewx, nginx
        update_cache: yes
       
      # SDR driver: https://github.com/matthewwall/weewx-sdr
      # https://github.com/matthewwall/weewx-sdr/issues/183  for the 5.0 version
    - name: get the SDR driver
      #ansible.builtin.shell: wget -O weewx-sdr.zip https://github.com/matthewwall/weewx-sdr/archive/master.zip
      ansible.builtin.shell: weectl extension install https://github.com/matthewwall/weewx-sdr/archive/master.zip

      
    - name: Add weewx user to adm group
      ansible.builtin.user:
        name: weewx
        groups: 
          - weewx
          - adm
          - plugdev

    - name: create the custom weewx SSD directories
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        mode: '0755'
        owner: weewx
      loop:
        - "{{ weewx_html }}"
        - "{{ weewx_database }}"
        
    - name: create weewx conf file
      ansible.builtin.template:
        src: weewx.conf
        dest: "{{ weewx_root }}/weewx.conf"
        mode: '0644'
      
    - name: create nginx conf file
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'
        
    - name: restart weewx service
      ansible.builtin.service:
        name: weewx
        state: restarted
        enabled: yes

    - name: disable lighttpd
      ansible.builtin.service:
        name: lighttpd
        state: stopped
        enabled: no
      ignore_errors: yes
        
    - name: restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
        
    - name: Create safe database backup
      cron:
        name: "weewx database backup"
        minute: "12"
        job: "sqlite3 {{ weewx_database }}/weewx.sdb \".timeout 2000\" \".backup weewx-backup.sdb\""
